packages:
  # all packages in direct subdirs of packages/
  - 'packages/web-core-cli'
  - 'packages/web-core-plus'
  - 'packages/wu-core-router'
  - 'packages/wu-build-tools'
  - 'packages/wu-component-icon'
  - 'component/packages/*'
  - 'component'
  # exclude packages that are inside test directories
